config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/index'
  end

  namespace :admin do
    get 'orders/show'
  end

  resource :cart, controller: "cart", only: [:show, :update, :edit] do
    member do
      post :add_product
      post :remove_product
      get  :confirmation
      post :finish
    end
  end

  namespace :admin do
    root to: 'products#index'
    resources :products
    resources :categories
    resources :orders, only: [:show, :index, :update]
  end

	get 'regulamin', 						to: "static#terms", 	 as: :terms
	get 'polityka-prywatnosci', to: "static#privacy",  as: :privacy
	get 'dostawa', 							to: "static#shipping", as: :shipping
	get 'o-sklepie', 						to: "static#about", 	 as: :about

  root to: "products#index"
  resources :products, 	 only: [:show, :index], path: "produkt"
  resources :categories, only: [:show], 				path: "kategoria"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order

  validates :first_name, :last_name, :zip_code, :street, :email, :city, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	validates :name, presence: true

	def to_param
		"#{id}-#{name}".parameterize
	end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def full_price
  	unit_price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries
  belongs_to :shipping_type
  has_many :line_items
  has_one :address
  has_many :transitions, class_name: "OrderTransition", autosave: false

  accepts_nested_attributes_for :address

  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
                  to: :state_machine

  def state_machine
  	@state_machine ||= OrderStateMachine.new(self, transition_class: OrderTransition,
  												  association_name: :transitions)
  end

  def full_cost
  	line_items.map { |e| e.full_price }.sum + shipping_cost
  end

  def self.transition_class
    OrderTransition
  end

  def self.initial_state
    OrderStateMachine.initial_state
  end

  def self.transition_name
    :transitions
  end
end

app/models/order_state_machine.rb
class OrderStateMachine
  include Statesman::Machine

  state :new, initial: true
  state :confirmed
  state :in_progress
  state :shipped
  state :cancelled

  transition from: :new, to: [:confirmed, :cancelled]
  transition from: :confirmed, to: [:in_progress, :cancelled]
  transition from: :in_progress, to: [:shipped, :cancelled]
  transition from: :shipped, to: [:cancelled]


  after_transition(to: :cancelled) do |order, transition|
    OrderMailer.order_cancelled(order).deliver
  end

  after_transition(to: :confirmed) do |order, transition|
    OrderMailer.order_confirmation(order).deliver
  end

  after_transition(to: :in_progress) do |order, transition|
    OrderMailer.order_in_progress(order).deliver
  end

  after_transition(to: :shipped) do |order, transition|
    OrderMailer.order_shipped(order).deliver
  end

  def self.states_map
    {
      "new" => "Niepotwierdzone",
      "confirmed" => "Złożone przez klienta",
      "in_progress" => "Przyjęte do realizacji",
      "shipped" => "Wysłane",
      "cancelled" => "Anulowane",
    }
  end
end

app/models/order_transition.rb
class OrderTransition < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordTransition


  belongs_to :order, inverse_of: :transitions

  after_destroy :update_most_recent, if: :most_recent?

  private

  def update_most_recent
    last_transition = order.order_transitions.order(:sort_key).last
    return unless last_transition.present?
    last_transition.update_column(:most_recent, true)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name,			  presence: true
  validates :description, presence: true
  validates :price, 			numericality: { greater_than: 0.0 }
  validates :category,		presence: true

  mount_uploader :photo, ProductPhotoUploader

  def to_param
		"#{id}-#{name}".parameterize
	end
end

app/models/shipping_type.rb
class ShippingType < ApplicationRecord
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	layout 'admin'

	before_action :authenticate

	def authenticate
		authenticate_or_request_with_http_basic 'Podaj hasło!' do |name, password|
			name == 'username' && password == 'secret'
		end
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @q = Product.ransack(params[:q])
  	@products = @q.result(distinct: true).page(params[:page]).per(30)
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to admin_products_path, notice: "Pomyślnie dodano produkt."
  	else
  		render action: :new
  	end
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update_attributes(product_params)
  		redirect_to admin_products_path, notice: "Pomyślnie zmieniono produkt"
  	else
  		render action: :edit
  	end
  end

  private

  	def product_params
  		params.require(:product).permit(
  			:name,
  			:category_id,
  			:description,
  			:long_description,
  			:price,
  			:photo
  		)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  def current_cart
  	if session[:order_id]
  		Order.find(session[:order_id])
  	else
  		Order.new
  	end
  end

  def current_cart_or_create
  	c = current_cart
  	if c.new_record?
  		c.save
  		session[:order_id] = c.id
  	end
  	c
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cart = current_cart
  end

  def edit
    @cart = current_cart
    @cart.build_address if @cart.address.blank?
  end

  def update
    @cart = current_cart
    if @cart.update_attributes(cart_attributes)
      @cart.update_attribute(:shipping_cost, @cart.shipping_type.cost)
      redirect_to confirmation_cart_path
    else
      render action: :edit
    end
  end

  def confirmation
    @cart = current_cart
  end

  def finish
    @cart = current_cart
    @cart.transition_to :confirmed
    session.delete(:order_id)
    flash[:notice] = "Dziękujemy za zamówienie!"
    redirect_to root_path
  end

  def add_product
    order = current_cart_or_create
    product = Product.find(params[:product_id])
    if item = order.line_items.where(product: product).first
      item.quantity += 1
      item.save
    else
      order.line_items.create product: product,
      quantity: 1,
      unit_price: product.price,
      item_name: product.name
    end
    redirect_to :back, notice: "Dodano produkt do koszyka"
  end

  def remove_product
    order = current_cart
    product = Product.find(params[:product_id])
    item = order.line_items.where(product: product).first
    if item
      item.destroy
    end
    redirect_to :back, notice: "Usunięto produkt z koszyka"
  end

  private

  def cart_attributes
    params.require(:order).permit(
      :shipping_type_id,
      :comment,
      :address_attributes => [
        :first_name,
        :last_name,
        :city,
        :zip_code,
        :street,
        :email
      ]
    )
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@products = @category.products.page(params[:page]).per(6)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.order(created_at: :desc).limit(9)
  end

  def show
  	@product = Product.find(params[:id])
  	@category = @product.category
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def terms
  end

  def privacy
  end

  def shipping
  end

  def about
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :long_description %>
	<%= f.input :price %>
	<%= f.association :category %>
	<%= f.input :photo %>
	<%= f.submit %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Admin::Products#edit</h1>
<p>Find me in app/views/admin/products/edit.html.erb</p>

app/views/admin/products/index.html.erb
<h1>Produkty</h1>

<%= link_to new_admin_product_path, class: "btn btn-success" do %>
	<span class="fa fa-plus"></span> Dodaj nowy produkt
<% end %>

<div class="search-form">
	<%= search_form_for [:admin, @q] do |f| %>
		<%= f.text_field :name_or_description_or_long_description_cont, placeholder: "Szukaj tekstu" %>
		<%= f.text_field :price_gt, placeholder: "Cena >" %>
		<%= f.submit "Szukaj" %>
	<% end %>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th><%= sort_link(@q, :name, "Nazwa") %></th>
			<th><%= sort_link(@q, :price, "Cena") %></th>
			<th><%= sort_link(@q, :category, "Kategoria") %></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
			<tr>
				<td><%= product.name %></td>
				<td><%= number_to_currency product.price %></td>
				<td><%= product.category.name %></td>
				<td>
					<%= link_to "Edycja", edit_admin_product_path(product), class: "btn btn-default btn-xs" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @products %>

app/views/admin/products/new.html.erb
<h1>Dodawanie produktu</h1>

<%= render 'form' %>

app/views/products/_products.html.erb
<% products.each_slice(3) do |slice| %>
	<div class="row">
		<% slice.each do |product| %>
			<div class="col-md-4">
				<div class="thumbnail">
					<%= link_to product_path(product) do %>
						<%= image_tag product.photo.url(:thumb) %>
					<% end %>
					<div class="caption">
						<h3><%= link_to product.name, product %></h3>
						<p><%= simple_format(truncate(product.description, length: 90)) %></p>
						<p class="lead"><%= number_to_currency product.price %></p>
						<p>
							<%= link_to add_product_cart_path(product_id: product.id), method: :post,
									class: "btn btn-primary" do %>
								<span class="a fa-shopping-cart"></span> Dodaj do koszyka
							<% end %>
						</p>
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/products/index.html.erb
<h1>Najnowsze produkty</h1>

<%= render partial: 'products', locals: { products: @products } %>

app/views/products/show.html.erb
<div class="container-fluid">
	<div class="col-md-5">
		<h1><%= @product.name %></h1>
		<p class="lead"><%= @product.description %></p>
		<%= simple_format(@product.long_description) %>

		<p class="lead"><%= number_to_currency(@product.price) %></p>
		<p>
			<%= link_to add_product_cart_path(product_id: @product.id), method: :post,
					class: "btn btn-primary" do %>
				<span class="fa fa-shopping-cart"> Dodaj do koszyka
			<% end %>
		</p>
	</div>
	<div class="col-md-7">
		<%= image_tag @product.photo.url(:details), class: "img-responsive" %>
	</div>
</div>